### ISSUE TITLE
Filter age contnues to increase

### ISSUE THREAD

**Issue by alexd106** [3ative/ikea-air-filter#1]
Hi, 

Firstly, thanks very much for your excellent tutorials. Really fun to watch and follow.

I am following your IKEA filter tutorial and have run into an issue whereby the filter age continues to increase regardless if the fan is off or on. I can reset but it continues to increase regardless. Everything else works fine, but i did have to cut the trace between R13 and the microcontroller (not sure if this is relevant).

I am using one of [these](https://www.amazon.co.uk/gp/product/B09C1F1475/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1)  instead of a D1 mini, so am not sure if this is the cause of the problem. Everything is wired up as per the tutorial.

I used a 10K resistor between the FG solder pad and pin D6. 

Thanks

**Comment by 3ative** [comment]
As there was a need to cut the track on the White Wire solder point, as there seemed to be different version of the IKEA controller board. There may also be a need to cut a track on the counter (Blue Wire)

Try this... Either cut the track (marked with an "X") **OR** remove resistor "R10" (circled)
![image](https://github.com/3ative/ikea-air-filter/assets/51385971/d9e491e1-e364-41b2-a814-ceaa220fa288)

**Comment by 3ative** [comment]
Also, please take a close-up photo of your board - So I can see what the differences could be. Thanks.

**Comment by alexd106** [comment]
Thanks a million for replying so quickly. Cutting the track on the counter has done the trick. 
See below for a photo of the board I have. Please forgive the shoddy photo and soldering!

![20240121_200145_004](https://github.com/3ative/ikea-air-filter/assets/8590989/b470cbf0-9faf-4c6c-841a-89d3139d10c9)

**Comment by 3ative** [comment]
Oh that's fantastic news - I'm glad that sorted it.  🥳

TBH: I have no Idea why mine works, I didn't need to cut any tracks.  Plus, your board looks exactly the same as mine!!!
 - I wonder if it's because I used a D1 Mini V3 ??
 
 Also, what happened to R15 LOL
 
![image](https://github.com/3ative/ikea-air-filter/assets/51385971/5cb8b911-699a-45ee-9a47-98e4b6f172c0)

**Comment by alexd106** [comment]
I don't think R15 was populated, at least that's my excuse! I am not the greatest at soldering (you make it look so easy) and i was worried  i accidently bridged the clock and R15 pad, so I just used solder wick to remove any excess solder.  Looks a bit ropey, but everything is working and no one except me will see it!

I don't have a D1 mini otherwise I would try it out. 

Thanks for all your help.

**Comment by 3ative** [comment]
> I don't think R15 was populated, at least that's my excuse! 

LOL - I've used that "reason" quite often myself.
 
> I don't have a D1 mini otherwise I would try it out.

Hmmm... the link you posted earlier are "D1 Minis" - Or at least a clone and are pretty much the same, except those are V2's. I guess they must be a little too sensitive 
> 
> Thanks for all your help.

You are most welcome. 🙏

**Comment by formatBCE** [comment]
BTW I can confirm R15 is missing on my board too. And I have same trouble with continuously increasing filter age.
Thanks for the hack!
@formatBCE aka CrossPoster on YouTube :)
